apiVersion: v1                 # Version de la API de Kubernetes
kind: Service                  # Tipo de recurso: Servicio
metadata:
  name: hola-mundo-service     # Nombre del servicio
spec:
  type: NodePort               # Tipo de servicio: NodePort (exponer puerto en cada nodo)
  selector:
    app: hola-mundo            # Selector: etiqueta de los Pods gestionados por este servicio
  ports:
  - protocol: TCP              # Protocolo utilizado
    port: 3000                 # Puerto interno del servicio
    targetPort: 3000           # Puerto del contenedor en los Pods
    nodePort: 30001            # Puerto en cada nodo para acceso externo
